repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: detect-aws-credentials
    -   id: check-case-conflict

-   repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.30.1  # The version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint
        files: infrastructure/cloudformation/.*\.(json|yml|yaml)$
