AWSTemplateFormatVersion: 2010-09-09
Description: 'Wordpress Application Stack'

Parameters:
  AppSubnet1Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Application Subnet 1"

  AppSubnet2Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Application Subnet 2"

  AppSubnet3Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Application Subnet 3"

  AppSecurityGroup:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: "Application Security Group Id"

  ParentStackName:
    Type: 'String'
    Description: 'Name of parent stack.'
    MinLength: 1

  AppLogRetentionDays:
    Type: 'Number'
    Description: 'Application log retention in days'
    MinValue: 1
    Default: 30

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', [/ecs, !Ref ParentStackName, app]]
      RetentionInDays: !Ref AppLogRetentionDays

  WpTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: "nginx:1.18.0-alpine"
          Name: "nginx-proxy"
          Essential: true
          Memory: 128
          PortMappings:
            - ContainerPort: 443
              HostPort: 443
            - ContainerPort: 80
              HostPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: wordpress
      NetworkMode: 'awsvpc'
      Memory: '512'
      Cpu: '256'


  ECSCluster:
    Type: AWS::ECS::Cluster

  WpService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: 'FARGATE'
      PropagateTags: 'SERVICE'
      SchedulingStrategy: 'REPLICA'
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: 'DISABLED'
          SecurityGroups:
            - !Ref AppSecurityGroup
          Subnets:
            - !Ref AppSubnet1Id
            - !Ref AppSubnet2Id
            - !Ref AppSubnet3Id
      TaskDefinition: !Ref WpTaskDefinition
