AWSTemplateFormatVersion: 2010-09-09
Description: 'Wordpress Full Stack (Existing VPC)'

Parameters:
  CustomCfnBucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Default: wp-cfn-deploy-s3-cloudformationbucket-1imzg0gegwkod
    Description: Custom Cloudformation Bucket Name hosting nested stack templates.
    Type: String
    MinLength: 1

  CustomCfnBucketRegion:
    Default: 'us-west-2'
    Description: The AWS Region where the custom S3 bucket (CustomCfnBucketName) is
      hosted. When using your own bucket, you must specify this value.
    Type: String
    MinLength: 1

  CustomCfnBucketPrefix:
    Default: '/v1'
    Description: Folder prefix for CustomCfnBucketName where cloudformation templates are present.
    Type: String

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: "VPC Id"

  VpnCidr:
    Type: "String"
    MinLength: 1
    Description: "Vpn Cidr (Use 0.0.0.0/32) if Vpn is not used"
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

  DbSubnet1Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Database Subnet 1"

  DbSubnet2Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Database Subnet 2"

  DbSubnet3Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Database Subnet 3"

  DbAutoPause:
    Default: 'true'
    Type: 'String'
    Description: 'Allow auto pause of database instance. Set it to false in production'
    AllowedValues:
      - 'true'
      - 'false'

  DbDeletionProtection:
    Default: 'false'
    Type: 'String'
    Description: 'Enable database deletion protection?'
    AllowedValues:
      - 'true'
      - 'false'

  AppSubnet1Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Application Subnet 1 (For Lambda Password Rotation)"

  AppSubnet2Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Application Subnet 2 (For Lambda Password Rotation)"

  AppSubnet3Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Application Subnet 3 (For Lambda Password Rotation)"

  PublicSubnet1Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public Subnet 1"

  PublicSubnet2Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public Subnet 2"

  PublicSubnet3Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public Subnet 3"

  ParentStackName:
    Type: 'String'
    Description: 'Name of parent stack. If not specified, it defaults to current stack name'
    MinLength: 0

  AppLogRetentionDays:
    Type: 'Number'
    Description: 'Application log retention in days'
    MinValue: 1
    Default: 30

  AlbAcmCertificateArn:
    Type: "String"
    MinLength: "1"
    Description: ARN For ACM Certificate to be used by ALB

  HostedZone:
    Type: String
    Description: "Hosted Zone Domain (e.g: example.com)"
    MinLength: 5
    AllowedPattern: '^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'

  LoadBalancerDnsName:
    Type: "String"
    MinLength: "1"
    Description: DNS Name for load balancer
    Default: "lb"

  SsmParameterKmsKeyAlias:
    Type: 'String'
    Description: 'Load balancer target group for associating ECS Service'
    Default: 'aws/ssm'
    MinLength: 1

  SsmNginxPrivateKey:
    Type: 'String'
    Description: |
      SSM Parameter store parameter holding Nginx SSL Private key (eg: /wordpress/ssl/server.key)
      The Nginx private key needs to be pre-generated and stored as a  SSM SecureString.
    MinLength: 1
    AllowedPattern: '^[/].*'

  SsmNginxCert:
    Type: 'String'
    Description: |
      SSM Parameter store parameter holding Nginx SSL public cert or bundled cert (eg: /wordpress/ssl/server.crt)
      Nginx public cert needs to be pre-generated and stored as a  SSM SecureString.
    MinLength: 1
    AllowedPattern: '^[/].*'

  DbPasswordRotationScheduleInDays:
    Type: 'Number'
    Description: |
      Rotate Database password in x days. The rotation requires wordpress app to be redeployed.
    MinValue: 1
    Default: 365

  EfsBackupCronSchedule:
    Type: "String"
    Description: "EFS Backup Cron Schedule"
    MinLength: 1
    Default: "0 0 ? * * *"

Conditions:
  IsParentStack: !Equals [!Ref ParentStackName, '']

Resources:
  VpcSecurity:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${CustomCfnBucketName}.s3.${CustomCfnBucketRegion}.${AWS::URLSuffix}/${CustomCfnBucketPrefix}/infrastructure/cloudformation/wp-vpc-security.yaml"
      Parameters:
        VpcId: !Ref VpcId
        VpnCidr: !Ref VpnCidr
    DeletionPolicy: "Delete"

  WpDatabase:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${CustomCfnBucketName}.s3.${CustomCfnBucketRegion}.${AWS::URLSuffix}/${CustomCfnBucketPrefix}/infrastructure/cloudformation/wp-db.yaml"
      Parameters:
        DbSubnet1Id: !Ref DbSubnet1Id
        DbSubnet2Id: !Ref DbSubnet2Id
        DbSubnet3Id: !Ref DbSubnet3Id
        AppSubnet1Id: !Ref AppSubnet1Id
        AppSubnet2Id: !Ref AppSubnet2Id
        AppSubnet3Id: !Ref AppSubnet3Id
        AutoPause:    !Ref DbAutoPause
        AuroraSecurityGroup: !GetAtt VpcSecurity.Outputs.AuroraSecurityGroup
        AppLambdaDbAccessSecurityGroup: !GetAtt VpcSecurity.Outputs.AppLambdaDbAccessSecurityGroup
        DeletionProtection: !Ref DbDeletionProtection
        ParentStackName:
          Fn::If:
            - IsParentStack
            - !Sub ${AWS::StackName}
            - !Ref ParentStackName
        DbPasswordRotationScheduleInDays: !Ref DbPasswordRotationScheduleInDays
    DeletionPolicy: "Delete"

  WpLoadBalancer:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${CustomCfnBucketName}.s3.${CustomCfnBucketRegion}.${AWS::URLSuffix}/${CustomCfnBucketPrefix}/infrastructure/cloudformation/wp-lb.yaml"
      Parameters:
        PublicSubnet1Id: !Ref PublicSubnet1Id
        PublicSubnet2Id: !Ref PublicSubnet2Id
        PublicSubnet3Id: !Ref PublicSubnet3Id
        AlbSecurityGroup:  !GetAtt VpcSecurity.Outputs.AlbSecurityGroup
        AlbAcmCertificateArn: !Ref AlbAcmCertificateArn
        HostedZone: !Ref HostedZone
        LoadBalancerDnsName: !Ref LoadBalancerDnsName
        VpcId: !Ref VpcId

  WpEfs:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${CustomCfnBucketName}.s3.${CustomCfnBucketRegion}.${AWS::URLSuffix}/${CustomCfnBucketPrefix}/infrastructure/cloudformation/wp-efs.yaml"
      Parameters:
        EfsSubnet1Id: !Ref DbSubnet1Id
        EfsSubnet2Id: !Ref DbSubnet2Id
        EfsSubnet3Id: !Ref DbSubnet3Id
        EfsSecurityGroup:  !GetAtt VpcSecurity.Outputs.EfsSecurityGroup
        EfsBackupCronSchedule: !Ref EfsBackupCronSchedule

  WpApp:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${CustomCfnBucketName}.s3.${CustomCfnBucketRegion}.${AWS::URLSuffix}/${CustomCfnBucketPrefix}/infrastructure/cloudformation/wp-app.yaml"
      Parameters:
        AppSubnet1Id: !Ref AppSubnet1Id
        AppSubnet2Id: !Ref AppSubnet2Id
        AppSubnet3Id: !Ref AppSubnet3Id
        AppSecurityGroup:  !GetAtt VpcSecurity.Outputs.AppSecurityGroup
        ParentStackName:
          Fn::If:
            - IsParentStack
            - !Sub ${AWS::StackName}
            - !Ref ParentStackName
        AppLogRetentionDays:  !Ref AppLogRetentionDays
        TargetGroupArn: !GetAtt WpLoadBalancer.Outputs.TargetGroupArn
        SsmParameterKmsKeyAlias: !Ref SsmParameterKmsKeyAlias
        SsmNginxPrivateKey: !Ref SsmNginxPrivateKey
        SsmNginxCert: !Ref SsmNginxCert
    DeletionPolicy: "Delete"
