AWSTemplateFormatVersion: 2010-09-09
Description: 'Wordpress LoadBalancer Stack'

Parameters:
  PublicSubnet1Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public Subnet 1"

  PublicSubnet2Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public Subnet 2"

  PublicSubnet3Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public Subnet 3"

  AlbSecurityGroup:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: "ALB Security Group Id"

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: "VPC Id"

  AlbAcmCertificateArn:
    Type: "String"
    MinLength: "1"
    Description: ARN For ACM Certificate to be used by ALB

  HostedZone:
    Type: String
    Description: "Hosted Zone Domain (e.g: example.com)"
    MinLength: 5
    AllowedPattern: '^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'

  LoadBalancerDnsName:
    Type: "String"
    MinLength: "1"
    Description: DNS Name for load balancer
    Default: "lb"



Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        # this is the default, but is specified here in case it needs to be changed
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      # "internal" is also an option
      Scheme: internet-facing
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
        - !Ref PublicSubnet3Id

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # HealthCheckIntervalSeconds: 10
      # will look for a 200 status code by default unless specified otherwise
      # HealthCheckPath: !Ref HealthCheckPath
      # HealthCheckTimeoutSeconds: 5
      # UnhealthyThresholdCount: 2
      # HealthyThresholdCount: 2
      Port: 443
      Protocol: HTTPS
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "60" # default is 300
      TargetType: ip
      VpcId: !Ref VpcId

  ListenerHttps:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AlbAcmCertificateArn

  AlbDnsRecords:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "${LoadBalancerDnsName}.${HostedZone}."
      HostedZoneName: !Sub ${HostedZone}.
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.DNSName
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
      Type: A

Outputs:
  TargetGroupArn:
    Description: Default target group ARN for wordpress load balancer
    Value: !Ref TargetGroup

  AlbDnsRecord:
    Description: Route53 record value for ALB
    Value: !Ref AlbDnsRecords
