AWSTemplateFormatVersion: 2010-09-09
Description: 'Wordpress LoadBalancer Stack'

Parameters:
  PublicSubnet1Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public Subnet 1"

  PublicSubnet2Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public Subnet 2"

  PublicSubnet3Id:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public Subnet 3"

  AlbSecurityGroup:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: "ALB Security Group Id"

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: "VPC Id"

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        # this is the default, but is specified here in case it needs to be changed
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      # "internal" is also an option
      Scheme: internet-facing
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
        - !Ref PublicSubnet3Id

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # HealthCheckIntervalSeconds: 10
      # will look for a 200 status code by default unless specified otherwise
      # HealthCheckPath: !Ref HealthCheckPath
      # HealthCheckTimeoutSeconds: 5
      # UnhealthyThresholdCount: 2
      # HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "60" # default is 300
      TargetType: ip
      VpcId: !Ref VpcId

  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
#      Certificates:
#        - CertificateArn: !Ref Certificate

Outputs:
  TargetGroupArn:
    Description: Default target group ARN for wordpress load balancer
    Value: !Ref TargetGroup
